### ISSUE TITLE
bandit_exclude not working

### ISSUE THREAD

**Issue by Babarberousse** [Wanderu/pytest-bandit#11]
Although the `bandit_exclude` parameter is not documented it is used in the code but it makes pytest crash when we actually use it.

Here's a pytest.ini to test it:
```
[pytest]
bandit_exclude = somedir
```

I made a quick fix there if you are ok with it: https://github.com/Wanderu/pytest-bandit/pull/10

**Comment by mattwwarren** [comment]
Very ok with it. Thank you for the pull request!
