### ISSUE TITLE
Make source archives available in pypi.org

### ISSUE THREAD

**Issue by jarkkorantala** [Wanderu/pytest-bandit#14]
Currently only wheels are published in [pypi.org](https://pypi.org/project/pytest-bandit/#files).

To enable repackaging for Conda, it would be beneficial to also publish source archives (`python -m setuptools sdist`). [Conda PyPi skeleton builder](https://docs.conda.io/projects/conda-build/en/latest/user-guide/tutorials/build-pkgs-skeleton.html) knows to look for source archives, but not for wheels.

**Comment by mattwwarren** [comment]
Should be available now! Sorry for not having those available. This is our first stab at distributing OSS software.
