### ISSUE TITLE
Travis.org is shutting down

### ISSUE THREAD

**Issue by tomdottom** [Wanderu/pytest-bandit#23]
From travis-ci.org

> Please be aware travis-ci.org will be shutting down in several weeks, with all accounts migrating to travis-ci.com. Please stay tuned here for more information.

From https://blog.travis-ci.com/2020-11-02-travis-ci-new-billing

> - We will be offering an allotment of OSS minutes that will be reviewed and allocated on a case by case basis. Should you want to apply for these credits please open a request with Travis CI support stating that you’d like to be considered for the OSS allotment. Please include:
>    - Your account name and VCS provider (like travis-ci.com/github/[your account name] )
>    - How many credits (build minutes) you’d like to request (should your run out of credits again you can repeat the process to request more or discuss a renewable amount)

**Comment by mattwwarren** [comment]
Seems like we could run with travis-ci.com or set up Actions. I'm tempted to experiment with the latter but open to influence.

**Comment by mattwwarren** [comment]
Scooped this up out of curiosity. #28 should fix this and seems to be an easy switch.

**Comment by mattwwarren** [comment]
And it was.
