### ISSUE TITLE
Remove Python 2.7 from python_requires

### ISSUE THREAD

**Issue by tucked** [Wanderu/pytest-bandit#8]
https://github.com/Wanderu/pytest-bandit/blob/42af2fd72e385502bac3258f31fb2f868d20b640/setup.py#L26

The trove classifiers do not include 2.7, though, and if you try to run with it, a `TypeError` occurs on `super`:
https://github.com/Wanderu/pytest-bandit/blob/42af2fd72e385502bac3258f31fb2f868d20b640/pytest_bandit/controller.py#L20

**Comment by mattwwarren** [comment]
Hm, good catch. I will make an update for this today. It's easier to drop support for python<3 than support it for 7 months.

**Comment by mattwwarren** [comment]
😅 Thanks for the PR. I rabbit holed on solving a different issue. This is available in v0.5.0 now on pypi!

**Comment by tucked** [comment]
All good 👍 I prefer opening PRs anyways when I have the bandwidth.
